TOP_SRCDIR = ../..
include $(TOP_SRCDIR)/Makefile.common

all: asin.o atan2.o atan.o ceil.o exp.o fabs.o floor.o fmod.o hugeval.o \
     isnan.o ldexp.o log10.o log.o pow.o sin.o sinh.o sqrt.o tan.o tanh.o

clean:
	rm -f *.o
