#!/bin/sh
image=sdcard.img
size=36				# in Megabytes

# Make a 36M image to start with
dd if=/dev/zero of=$image bs=1M count=$size

# Put in a partition table with an 18M FAT32
# partition and an 18M UDF partition which
# xv6 will use.
/sbin/parted $image mklabel msdos
/sbin/parted $image mkpart primary fat32 1MB 50%
/sbin/parted $image mkpart primary udf 50% 100%
/sbin/parted $image print

# Make the FAT32 filesystem
/sbin/mkfs.vfat -F 32 --offset=2048 $image

# Copy the xv6 binary to the FAT32 partition
mcopy -i "$image"@@1M /usr/local/src/xv6-rosco-r2/kern/xv6.bin ::RosCode1.bin

# Print out the FAT32 contents
mdir -i "$image"@@1M

# Now copy the FAT32 filesystem to a temp file and
# append the xv6
dd if=$image of=temp.img bs=1M count=18
cat /usr/local/src/xv6-rosco-r2/fs.img >> temp.img
mv temp.img $image
