TOP_SRCDIR = ../..
include $(TOP_SRCDIR)/Makefile.common

all: bcmp.o bcopy.o bzero.o crypt.o ctermid.o cuserid.o \
     environ.o errno.o execlp.o fdopen.o ffs.o fputk.o \
     getdents.o getgrent.o getgroups.o getlogin.o getopt.o \
     getpass.o getpw.o getpwent.o getw.o hypot.o index.o itoa.o loadname.o \
     lock.o _longjerr.o lrand.o lsearch.o memccpy.o mktemp.o mtab.o \
     popen.o putenv.o putk.o putw.o regexp.o \
     regsub.o rindex.o stderr.o swab.o syscall.o \
     sysconf.o syslib.o taskcall.o termcap.o ttyname.o \
     fprintk.o printk.o readline.o readline_fn.o
# fslib.o fsversion.o nlist.o

clean:
	rm -f *.o
